apiVersion: v1
kind: Service
metadata:
  # must be the same as the StatefulSet spec.serviceName
  name: elasticsearch-headless
  namespace: kube-logging
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  # headless service, can be used by elastic Pods to contact each other
  clusterIP: None
  ports:
  - name: rest
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: inter-node
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: elasticsearch